apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocrmodel-chart.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocrmodel
  template:
    metadata:
      labels:
        app: ocrmodel
    spec:
      containers:
        - name: ocrmodel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: regcred  # Hardcoded secret name here

