apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  selector:
    app: apigateway
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}

  type: NodePort

